FROM python:3.9

RUN apt-get update

WORKDIR /usr/src/

COPY ./apps /usr/src/apps
COPY ./requirements.txt /usr/src/requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN echo "building..."

